---
apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: mobsf # You can specify any app name here
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: registry.jetbrains.team/p/scanner-for-plugins/containers/mobsf # Must match you container image path from Space
      context: ../
      docker:
        dockerfile: ../Dockerfile
  local:
    useDockerCLI: false
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: mobsf
        remoteChart: oci://registry.jetbrains.team/p/cb/helm-charts/simple-app # You can leave it or specify any your helm chart or from your repo
        version: 0.2.0
        setValueTemplates:
          image: "{{.IMAGE_FULLY_QUALIFIED}}"
          imagePullSecret: "{{.IMAGE_PULL_SECRET}}"
          applicationName: "{{.APPLICATION_NAME}}"
        valuesFiles:
          - values.yaml
